# Travis CI

## I prefer to explicitly send my builds to the container-based infrastructure
sudo: false

## The programmming language that I use
language: python

## Choosing Python versions to test against
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

## Command to install dependencies before
before_script:
  - chmod +x .travis/install.sh
  - .travis/install.sh

## Command to run tests
script: nosetests

## Disallow notifications
notifications:
  email: false

## Run tests only for this git branches 
branches:
  only:
    - master
